baseurl = "https://blog.missingsemester.in/"
title = "A place for whatever I feel like sharing"
theme = "terminal"
languageCode = "en"
timeZone = "Asia/Kolkata"

[pagination]
pagerSize = 20

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github-dark"

[params]
contentTypeName = "posts"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true
autoCover = true
showPagination = true
showReadingTime = true
showLastUpdated = true

# Keep custom params for avatar and info
info = "I like to read (a lot) .... and write (maybe)."
avatarurl = "img/avatar.png"

# Favicon settings
favicon = "img/favicon.ico"
faviconSVG = "img/favicon.svg"
favicon_32 = "img/favicon-32x32.png"
favicon_16 = "img/favicon-16x16.png"

# Theme settings
enableTwemoji = true
colorScheme = "auto"
since = 2026

# Custom CSS
customCSS = ["css/custom.css"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[caches]
[caches.images]
dir = ':cacheDir/images'

# Language settings (Terminal theme uses languages structure)
[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.en.params]
logoText = "A place for whatever I feel like sharing"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 1

[[languages.en.menu.main]]
identifier = "influences"
name = "Influences"
url = "/influences"
weight = 2

[[languages.en.menu.main]]
identifier = "readings"
name = "Readings"
url = "/readings"
weight = 3

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 4

# Social links (Terminal theme format)
[[languages.en.menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/vineetverma321/"
weight = 10

[[languages.en.menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/vineetverma321/"
weight = 11
